/*
 * Application Package Management API on Mm1
 *
 * The ETSI GS MEC 010-2 Application Application Package Management API described using OpenAPI
 *
 * API version: 2.0.13
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"github.com/lib/pq"
)

// SecurityInfoOAuth2Info - Parameters related to use of OAuth 2.0
type SecurityInfoOAuth2Info struct {

	// List of supported OAuth 2.0 grant types.
	GrantTypes pq.StringArray `gorm:"type:text[]" json:"grantTypes"`
	// The token endpoint
	TokenEndpoint string `json:"tokenEndpoint"`
}
