/*
 * Application Package Management API on Mm1
 *
 * The ETSI GS MEC 010-2 Application Application Package Management API described using OpenAPI
 *
 * API version: 2.0.13
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// SecurityInfoOAuth2InfoGrantType : List of supported OAuth 2.0 grant types
type SecurityInfoOAuth2InfoGrantType string

// List of SecurityInfo.OAuth2Info.GrantType
const (
	AUTHORIZATION_CODE SecurityInfoOAuth2InfoGrantType = "OAUTH2_AUTHORIZATION_CODE"
	IMPLICIT_GRANT     SecurityInfoOAuth2InfoGrantType = "OAUTH2_IMPLICIT_GRANT"
	RESOURCE_OWNER     SecurityInfoOAuth2InfoGrantType = "OAUTH2_RESOURCE_OWNER"
	CLIENT_CREDENTIALS SecurityInfoOAuth2InfoGrantType = "OAUTH2_CLIENT_CREDENTIALS"
)

// var securityInfoOAuth2InfoGrantTypeArray = map[SecurityInfoOAuth2InfoGrantType]string{
// 	AUTHORIZATION_CODE: "OAUTH2_AUTHORIZATION_CODE",
// 	IMPLICIT_GRANT:     "OAUTH2_IMPLICIT_GRANT",
// 	RESOURCE_OWNER:     "OAUTH2_RESOURCE_OWNER",
// 	CLIENT_CREDENTIALS: "OAUTH2_CLIENT_CREDENTIALS",
// }
//
// func (security_info_oauth2_info_grant_type SecurityInfoOAuth2InfoGrantType) String() string {
// 	return securityInfoOAuth2InfoGrantTypeArray[security_info_oauth2_info_grant_type]
// }
//
// func (u *SecurityInfoOAuth2InfoGrantType) Scan(value interface{}) error {
// 	str, ok := value.(string)
// 	if !ok {
// 		return errors.New(fmt.Sprint("Unmarshal SecurityInfoOAuth2InfoGrantType value failed", value))
// 	}
// 	*u = SecurityInfoOAuth2InfoGrantType(str)
// 	return nil
// }
//
// func (u SecurityInfoOAuth2InfoGrantType) Value() (driver.Value, error) {
// 	if len(u) == 0 {
// 		return nil, nil
// 	}
//
// 	if ret, ok := securityInfoOAuth2InfoGrantTypeArray[u]; ok {
// 		return ret, nil
// 	} else {
// 		return nil, errors.New("SecurityInfoOAuth2InfoGrantType type error.")
// 	}
// }
