/*
 * Application Package Management API on Mm1
 *
 * The ETSI GS MEC 010-2 Application Application Package Management API described using OpenAPI
 *
 * API version: 2.0.13
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import uuid "github.com/satori/go.uuid"

// SecurityInfo - This type represents security information related to a transport
type SecurityInfo struct {
	Model
	TransportDescriptorID uuid.UUID `json:"-"`

	SecurityInfoID uuid.UUID `gorm:"primarykey;type:uuid;default:uuid_generate_v4();" json:"id"`

	OAuth2Info SecurityInfoOAuth2Info `gorm:"embedded" json:"oAuth2Info,omitempty"`
}
